import { localePath, type Locale } from "@/lib/i18n/config";

/**
 * Fill with CEIDG data before launch. Do not invent real values.
 * If `[EMAIL_PUBLICZNY]` stays a Gmail address, set `[DOSTAWCA_SKRZYNKI]` to Google.
 */
export const LEGAL_OPERATOR_NAME = "[NAZWA_JDG]";
export const LEGAL_OPERATOR_NIP = "[NIP]";
export const LEGAL_OPERATOR_ADDRESS = "[ADRES_DZIALALNOSCI]";
export const PRIVACY_CONTROLLER_EMAIL = "[EMAIL_PUBLICZNY]";
export const LEGAL_INBOX_PROVIDER = "[DOSTAWCA_SKRZYNKI]";

export type LegalPageKey = "privacy" | "terms";

export type LegalSection = {
  heading: string;
  paragraphs?: string[];
  items?: string[];
};

export type LegalContent = {
  title: string;
  description: string;
  lastUpdatedLabel: string;
  lastUpdated: string;
  backHomeLabel: string;
  sections: LegalSection[];
};

const lastUpdated = {
  en: "15 August 2026",
  pl: "15 sierpnia 2026",
} satisfies Record<Locale, string>;

const legalContent = {
  en: {
    privacy: {
      title: "Privacy Policy",
      description:
        "How personal data is processed on bjaniuk.com, including the contact form, antispam protection, analytics, and browser storage. This page also fulfils the Article 13 GDPR information notice.",
      lastUpdatedLabel: "Last updated",
      lastUpdated: lastUpdated.en,
      backHomeLabel: "Back to home",
      sections: [
        {
          heading: "1. Data controller",
          paragraphs: [
            `The controller of personal data processed through bjaniuk.com is ${LEGAL_OPERATOR_NAME}, a sole trader (JDG) registered in Poland. NIP: ${LEGAL_OPERATOR_NIP}. Place of business: ${LEGAL_OPERATOR_ADDRESS}.`,
            `Contact: ${PRIVACY_CONTROLLER_EMAIL} or the contact form on this website. No Data Protection Officer has been appointed. Data-subject requests can be sent to the controller contact above.`,
          ],
        },
        {
          heading: "2. What data is processed",
          paragraphs: [
            "When you use the contact form, the website processes the email address, subject, and message content that you provide, together with submission status.",
            "For antispam protection, Cloudflare Turnstile may process technical signals such as a security token, IP address, user-agent, TLS/browser signals, site key, action, and hostname.",
            "The hosting and analytics layer may process technical request data such as URL, referrer, approximate location, device type, browser, operating system, timestamp, and bot-detection signals. Vercel Web Analytics is configured as cookieless analytics and is used for aggregated traffic statistics.",
            "The website stores the selected theme preference in the browser's localStorage under the key `theme-mode`. This is used only to remember the visual theme selected by the visitor.",
            "Contact-form data comes from you. Technical security, hosting, and analytics data is generated by your device, browser, and the providers that operate the website.",
          ],
        },
        {
          heading: "3. Purposes and legal bases",
          items: [
            "Replying to contact-form messages and handling correspondence - Article 6(1)(f) GDPR (legitimate interest in handling correspondence). Where the message concerns potential cooperation, Article 6(1)(b) GDPR may also apply (steps prior to entering into a contract).",
            "Protecting the contact form and website against spam, bots, abuse, and attacks - Article 6(1)(f) GDPR.",
            "Maintaining hosting, diagnostics, logs, and basic aggregated website analytics - Article 6(1)(f) GDPR, legitimate interest in measuring and improving the website without advertising profiling.",
            "Remembering the selected theme in localStorage - Article 6(1)(f) GDPR, legitimate interest in preserving a user-selected interface preference.",
          ],
        },
        {
          heading: "4. Recipients and tools",
          paragraphs: [
            "The website uses selected service providers only to run the website and process contact requests. Data may also be disclosed where required by law or necessary to establish, exercise, or defend legal claims.",
          ],
          items: [
            "Vercel - hosting, deployment infrastructure, request handling, and cookieless Web Analytics.",
            "Resend - delivery of messages submitted through the contact form to the controller inbox.",
            "Cloudflare Turnstile - antispam and bot-protection verification for the contact form.",
            "Sanity - CMS and content/image delivery for public website content.",
            `${LEGAL_INBOX_PROVIDER} - storage and handling of received contact messages in the controller inbox.`,
          ],
        },
        {
          heading: "5. Transfers outside the EEA",
          paragraphs: [
            "Some providers may process data outside the European Economic Area, including in the United States. Where this happens, the controller relies on appropriate safeguards described by those providers, in particular the European Commission's standard contractual clauses (SCCs) and, where a provider is certified, the EU-US Data Privacy Framework. A copy of the relevant safeguards can be requested from the controller or reviewed in the provider's legal documentation.",
          ],
        },
        {
          heading: "6. Retention",
          items: [
            "Contact-form messages: for as long as needed to reply, then for an archive period of up to 12 months after the correspondence is closed, unless a longer period is required by law or is necessary to establish, exercise, or defend legal claims.",
            "Security, hosting, and diagnostic logs: according to the retention periods of the relevant providers and only as needed for security, operations, and abuse prevention.",
            "Aggregated analytics: retained as aggregated statistics and not used to identify visitors.",
            "Theme preference: until you change the setting or clear browser storage.",
          ],
        },
        {
          heading: "7. Cookies, browser storage, and analytics",
          paragraphs: [
            "This website does not use advertising cookies and does not profile visitors for marketing. No separate cookie policy or cookie banner is used for the current tools.",
            "Vercel Web Analytics is cookieless and provides aggregated usage metrics.",
            "The website uses browser localStorage only for the theme preference under the key `theme-mode`. This is not a cookie. You can remove it by clearing site data in your browser.",
            "Cloudflare Turnstile is used only as a one-time security token check on the contact form. Pre-clearance cookies such as `cf_clearance` are not enabled by this website. Turnstile and the hosting layer may use technical signals necessary for security and abuse prevention.",
          ],
        },
        {
          heading: "8. Your rights",
          paragraphs: [
            "Under the GDPR, you may request access to your data, rectification, erasure, restriction of processing, data portability, and object to processing based on legitimate interests. If processing were ever based on consent, you would also have the right to withdraw that consent at any time.",
            `Requests can be sent to ${PRIVACY_CONTROLLER_EMAIL}. The controller may need additional information to confirm your identity before fulfilling a request.`,
            "You also have the right to lodge a complaint with a supervisory authority. In Poland, this is the President of the Personal Data Protection Office (UODO).",
          ],
        },
        {
          heading: "9. Voluntary data provision",
          paragraphs: [
            "Providing contact-form data is voluntary, but email address, subject, message content, and successful security verification are necessary to send and respond to a message. Without them, the website operator may be unable to respond.",
          ],
        },
        {
          heading: "10. Automated decision-making",
          paragraphs: [
            "The website does not use automated decision-making that produces legal or similarly significant effects. Turnstile performs an automated security check only to decide whether the contact form submission should be accepted as non-abusive. If the form is unavailable, you can contact the controller by email.",
          ],
        },
        {
          heading: "11. External links",
          paragraphs: [
            "The website may link to external websites or social profiles. Those external services are controlled by their own operators and their own privacy rules apply after you leave this website.",
          ],
        },
      ],
    },
    terms: {
      title: "Terms of Use",
      description:
        "Rules for using bjaniuk.com, a portfolio website operated as a sole tradership (JDG) by the service provider identified below.",
      lastUpdatedLabel: "Last updated",
      lastUpdated: lastUpdated.en,
      backHomeLabel: "Back to home",
      sections: [
        {
          heading: "1. Service provider",
          paragraphs: [
            `The website bjaniuk.com is operated by ${LEGAL_OPERATOR_NAME}, a sole trader (JDG) registered in Poland. NIP: ${LEGAL_OPERATOR_NIP}. Place of business: ${LEGAL_OPERATOR_ADDRESS}. Contact: ${PRIVACY_CONTROLLER_EMAIL}.`,
            "These Terms describe the rules for using the public portfolio website as an electronic service. The website does not create user accounts, sell products, process payments, or provide a subscription service.",
          ],
        },
        {
          heading: "2. Electronic services",
          paragraphs: [
            "The service provider makes the following free electronic services available: (1) browsing public portfolio pages, including experience, projects, technology stack, and experimental workbench pages; (2) sending a message through the contact form.",
            "Content on the website is informational and promotional. It is not legal, financial, tax, medical, or other regulated professional advice. Using the website does not by itself create a contract for paid work.",
          ],
        },
        {
          heading: "3. Technical requirements",
          paragraphs: [
            "To use the website you need a current web browser with JavaScript enabled, a stable internet connection, and, for the contact form, a working email address and completion of the antispam check.",
            "Electronic communication over the internet involves typical risks such as interruption, delay, or unauthorised access by third parties despite reasonable security measures. The operator uses hosting, transport encryption, and form antispam protection, but cannot eliminate those risks entirely.",
          ],
        },
        {
          heading: "4. Contact form",
          paragraphs: [
            "You may use the contact form to send a message to the service provider. You must provide true and non-misleading information and you must not use the form for spam, unlawful content, malware, automated abuse, or infringement of third-party rights.",
            "Submitting the contact form does not automatically create a contract. Any cooperation, commercial terms, deadlines, or project scope must be agreed separately.",
          ],
        },
        {
          heading: "5. Permitted use",
          paragraphs: [
            "You may browse the website for personal or business information purposes. You must not interfere with the website, bypass security controls, overload the service, scrape it in a disruptive way, attempt unauthorized access to systems used by the website, or supply unlawful content.",
          ],
        },
        {
          heading: "6. Intellectual property",
          paragraphs: [
            "Unless stated otherwise, website content, layout, graphics, code, and portfolio materials are protected by copyright or other intellectual-property rights.",
            "You may share links to public pages. Any reuse of content beyond quotation, private use, or other statutory exceptions requires prior permission from the operator or the relevant rights holder.",
          ],
        },
        {
          heading: "7. External services and links",
          paragraphs: [
            "The website may contain links to external websites, repositories, social profiles, or third-party services. The operator is not responsible for the content, availability, or rules of external services after you leave this website.",
          ],
        },
        {
          heading: "8. Availability and changes",
          paragraphs: [
            "The operator may update, suspend, or remove parts of the website at any time. The website is provided as a public portfolio and may be temporarily unavailable due to maintenance, hosting issues, security controls, or third-party service interruptions.",
          ],
        },
        {
          heading: "9. Liability",
          paragraphs: [
            "The operator makes reasonable efforts to keep the website accurate and secure, but cannot guarantee uninterrupted operation or that every public portfolio detail is always current.",
            "Nothing in these Terms limits liability where such limitation is not permitted by applicable law.",
          ],
        },
        {
          heading: "10. Complaints",
          paragraphs: [
            `Complaints about the website or the contact form can be sent to ${PRIVACY_CONTROLLER_EMAIL}. Describe the issue and how we can contact you. The operator will review the complaint and respond to the email address you provide, usually within 14 days.`,
          ],
        },
        {
          heading: "11. Privacy",
          paragraphs: [
            "Information about personal-data processing, including the Article 13 GDPR notice, browser storage, analytics, and contact-form handling, is available in the Privacy Policy.",
          ],
        },
        {
          heading: "12. Changes to these Terms",
          paragraphs: [
            "These Terms may be updated when the website, tools, or legal requirements change. The current version is published on this page with the date of the latest update.",
          ],
        },
      ],
    },
  },
  pl: {
    privacy: {
      title: "Polityka prywatności",
      description:
        "Jak przetwarzane są dane osobowe na bjaniuk.com, w tym dane z formularza kontaktowego, ochrony antyspamowej, analityki i pamięci przeglądarki. Ta strona spełnia też obowiązek informacyjny z art. 13 RODO.",
      lastUpdatedLabel: "Ostatnia aktualizacja",
      lastUpdated: lastUpdated.pl,
      backHomeLabel: "Wróć na stronę główną",
      sections: [
        {
          heading: "1. Administrator danych",
          paragraphs: [
            `Administratorem danych osobowych przetwarzanych w ramach bjaniuk.com jest ${LEGAL_OPERATOR_NAME}, prowadzący jednoosobową działalność gospodarczą (JDG) w Polsce. NIP: ${LEGAL_OPERATOR_NIP}. Adres wykonywania działalności: ${LEGAL_OPERATOR_ADDRESS}.`,
            `Kontakt: ${PRIVACY_CONTROLLER_EMAIL} albo formularz kontaktowy na tej stronie. Administrator nie wyznaczył inspektora ochrony danych. Żądania dotyczące danych osobowych można kierować na powyższy adres kontaktowy.`,
          ],
        },
        {
          heading: "2. Jakie dane są przetwarzane",
          paragraphs: [
            "Gdy korzystasz z formularza kontaktowego, strona przetwarza podany przez Ciebie adres e-mail, temat oraz treść wiadomości, a także status wysyłki.",
            "W celu ochrony przed spamem Cloudflare Turnstile może przetwarzać sygnały techniczne, takie jak token bezpieczeństwa, adres IP, user-agent, sygnały TLS/przeglądarki, site key, action i hostname.",
            "Warstwa hostingu i analityki może przetwarzać techniczne dane żądania, takie jak URL, referrer, przybliżona lokalizacja, typ urządzenia, przeglądarka, system operacyjny, znacznik czasu i sygnały wykrywania botów. Vercel Web Analytics jest używany jako analityka bez cookies i służy do zagregowanych statystyk ruchu.",
            "Strona zapisuje wybraną preferencję motywu w localStorage przeglądarki pod kluczem `theme-mode`. Służy to wyłącznie zapamiętaniu motywu wizualnego wybranego przez odwiedzającego.",
            "Dane z formularza pochodzą od Ciebie. Techniczne dane bezpieczeństwa, hostingu i analityki powstają po stronie Twojego urządzenia, przeglądarki oraz dostawców obsługujących stronę.",
          ],
        },
        {
          heading: "3. Cele i podstawy prawne",
          items: [
            "Odpowiadanie na wiadomości z formularza kontaktowego i prowadzenie korespondencji - art. 6 ust. 1 lit. f RODO (prawnie uzasadniony interes w prowadzeniu korespondencji). Gdy wiadomość dotyczy potencjalnej współpracy, może mieć zastosowanie także art. 6 ust. 1 lit. b RODO (działania przed zawarciem umowy).",
            "Ochrona formularza kontaktowego i strony przed spamem, botami, nadużyciami i atakami - art. 6 ust. 1 lit. f RODO.",
            "Utrzymanie hostingu, diagnostyki, logów i podstawowej zagregowanej analityki strony - art. 6 ust. 1 lit. f RODO, prawnie uzasadniony interes w mierzeniu i ulepszaniu strony bez profilowania reklamowego.",
            "Zapamiętanie wybranego motywu w localStorage - art. 6 ust. 1 lit. f RODO, prawnie uzasadniony interes w zachowaniu preferencji interfejsu wybranej przez użytkownika.",
          ],
        },
        {
          heading: "4. Odbiorcy i narzędzia",
          paragraphs: [
            "Strona korzysta z wybranych dostawców wyłącznie w celu działania serwisu i obsługi zapytań kontaktowych. Dane mogą być też ujawnione, gdy wymagają tego przepisy prawa albo gdy jest to konieczne do ustalenia, dochodzenia lub obrony roszczeń.",
          ],
          items: [
            "Vercel - hosting, infrastruktura wdrożeniowa, obsługa żądań i bezciasteczkowa Web Analytics.",
            "Resend - dostarczanie wiadomości wysłanych przez formularz kontaktowy do skrzynki administratora.",
            "Cloudflare Turnstile - antyspamowa i antybotowa weryfikacja formularza kontaktowego.",
            "Sanity - CMS oraz dostarczanie publicznych treści i obrazów strony.",
            `${LEGAL_INBOX_PROVIDER} - przechowywanie i obsługa odebranych wiadomości kontaktowych w skrzynce administratora.`,
          ],
        },
        {
          heading: "5. Przekazywanie danych poza EOG",
          paragraphs: [
            "Niektórzy dostawcy mogą przetwarzać dane poza Europejskim Obszarem Gospodarczym, w tym w Stanach Zjednoczonych. W takim przypadku administrator opiera się na odpowiednich zabezpieczeniach opisanych przez tych dostawców, w szczególności na standardowych klauzulach umownych Komisji Europejskiej (SCC) oraz, gdy dostawca jest certyfikowany, na programie EU-US Data Privacy Framework. Kopię właściwych zabezpieczeń można uzyskać od administratora albo przejrzeć w dokumentacji prawnej dostawcy.",
          ],
        },
        {
          heading: "6. Okres przechowywania",
          items: [
            "Wiadomości z formularza: tak długo, jak jest to potrzebne do odpowiedzi, a następnie przez okres archiwalny do 12 miesięcy od zakończenia korespondencji, chyba że dłuższy okres wynika z przepisów prawa albo jest konieczny do ustalenia, dochodzenia lub obrony roszczeń.",
            "Logi bezpieczeństwa, hostingu i diagnostyki: zgodnie z okresami stosowanymi przez właściwych dostawców i tylko w zakresie potrzebnym do bezpieczeństwa, działania strony oraz przeciwdziałania nadużyciom.",
            "Zagregowana analityka: przechowywana jako statystyka zbiorcza i nieużywana do identyfikacji odwiedzających.",
            "Preferencja motywu: do czasu zmiany ustawienia albo wyczyszczenia pamięci przeglądarki.",
          ],
        },
        {
          heading: "7. Cookies, pamięć przeglądarki i analityka",
          paragraphs: [
            "Ta strona nie używa reklamowych plików cookie i nie profiluje odwiedzających w celach marketingowych. Przy obecnych narzędziach nie jest stosowana osobna polityka cookies ani banner cookies.",
            "Vercel Web Analytics działa bez cookies i dostarcza zagregowane metryki użycia.",
            "Strona używa localStorage przeglądarki wyłącznie do preferencji motywu pod kluczem `theme-mode`. To nie jest plik cookie. Możesz go usunąć, czyszcząc dane strony w przeglądarce.",
            "Cloudflare Turnstile jest używany wyłącznie jako jednorazowa weryfikacja tokenu bezpieczeństwa przy formularzu kontaktowym. Ta strona nie włącza pre-clearance ani pliku cookie `cf_clearance`. Turnstile oraz warstwa hostingu mogą korzystać z sygnałów technicznych koniecznych dla bezpieczeństwa i przeciwdziałania nadużyciom.",
          ],
        },
        {
          heading: "8. Twoje prawa",
          paragraphs: [
            "Na podstawie RODO możesz żądać dostępu do swoich danych, ich sprostowania, usunięcia, ograniczenia przetwarzania, przenoszenia danych oraz wnieść sprzeciw wobec przetwarzania opartego na prawnie uzasadnionym interesie. Jeżeli jakiekolwiek przetwarzanie byłoby kiedykolwiek oparte na zgodzie, przysługiwałoby Ci także prawo jej cofnięcia w dowolnym momencie.",
            `Żądania można kierować na ${PRIVACY_CONTROLLER_EMAIL}. Administrator może potrzebować dodatkowych informacji w celu potwierdzenia Twojej tożsamości przed realizacją żądania.`,
            "Masz także prawo złożyć skargę do organu nadzorczego. W Polsce jest nim Prezes Urzędu Ochrony Danych Osobowych (UODO).",
          ],
        },
        {
          heading: "9. Dobrowolność podania danych",
          paragraphs: [
            "Podanie danych w formularzu jest dobrowolne, ale adres e-mail, temat, treść wiadomości i skuteczna weryfikacja bezpieczeństwa są konieczne do wysłania i obsłużenia wiadomości. Bez nich operator strony może nie być w stanie odpowiedzieć.",
          ],
        },
        {
          heading: "10. Zautomatyzowane podejmowanie decyzji",
          paragraphs: [
            "Strona nie stosuje zautomatyzowanego podejmowania decyzji wywołującego skutki prawne albo podobnie istotnie wpływającego na użytkownika. Turnstile wykonuje wyłącznie automatyczną kontrolę bezpieczeństwa, aby zdecydować, czy zgłoszenie z formularza powinno zostać przyjęte jako nienadużyciowe. Jeżeli formularz jest niedostępny, możesz skontaktować się z administratorem e-mailem.",
          ],
        },
        {
          heading: "11. Linki zewnętrzne",
          paragraphs: [
            "Strona może zawierać linki do zewnętrznych serwisów albo profili społecznościowych. Po opuszczeniu tej strony zastosowanie mają zasady prywatności właściwych operatorów zewnętrznych usług.",
          ],
        },
      ],
    },
    terms: {
      title: "Regulamin",
      description:
        "Zasady korzystania z bjaniuk.com, strony portfolio prowadzonej w ramach jednoosobowej działalności gospodarczej (JDG) przez usługodawcę wskazanego poniżej.",
      lastUpdatedLabel: "Ostatnia aktualizacja",
      lastUpdated: lastUpdated.pl,
      backHomeLabel: "Wróć na stronę główną",
      sections: [
        {
          heading: "1. Usługodawca",
          paragraphs: [
            `Strona bjaniuk.com jest prowadzona przez ${LEGAL_OPERATOR_NAME}, prowadzącego jednoosobową działalność gospodarczą (JDG) w Polsce. NIP: ${LEGAL_OPERATOR_NIP}. Adres wykonywania działalności: ${LEGAL_OPERATOR_ADDRESS}. Kontakt: ${PRIVACY_CONTROLLER_EMAIL}.`,
            "Niniejszy regulamin opisuje zasady korzystania z publicznej strony portfolio jako usługi świadczonej drogą elektroniczną. Strona nie tworzy kont użytkowników, nie sprzedaje produktów, nie obsługuje płatności i nie świadczy usługi subskrypcyjnej.",
          ],
        },
        {
          heading: "2. Usługi elektroniczne",
          paragraphs: [
            "Usługodawca udostępnia nieodpłatnie następujące usługi elektroniczne: (1) przeglądanie publicznych stron portfolio, w tym doświadczenia, projektów, stacku technologicznego oraz eksperymentalnych stron workbench; (2) wysłanie wiadomości przez formularz kontaktowy.",
            "Treści na stronie mają charakter informacyjny i promocyjny. Nie stanowią porady prawnej, finansowej, podatkowej, medycznej ani innej regulowanej porady profesjonalnej. Korzystanie ze strony samo w sobie nie zawiera umowy o płatną współpracę.",
          ],
        },
        {
          heading: "3. Wymagania techniczne",
          paragraphs: [
            "Do korzystania ze strony potrzebna jest aktualna przeglądarka z włączonym JavaScript, stabilne połączenie internetowe, a w przypadku formularza kontaktowego - działający adres e-mail i ukończenie weryfikacji antyspamowej.",
            "Komunikacja elektroniczna przez internet wiąże się z typowymi ryzykami, takimi jak przerwa, opóźnienie albo nieuprawniony dostęp osób trzecich mimo rozsądnych środków bezpieczeństwa. Operator korzysta z hostingu, szyfrowania transmisji i ochrony antyspamowej formularza, ale nie może tych ryzyk całkowicie wyeliminować.",
          ],
        },
        {
          heading: "4. Formularz kontaktowy",
          paragraphs: [
            "Możesz użyć formularza kontaktowego, aby wysłać wiadomość do usługodawcy. Podawane informacje powinny być prawdziwe i niewprowadzające w błąd. Formularza nie wolno używać do spamu, treści bezprawnych, malware, automatycznych nadużyć ani naruszania praw osób trzecich.",
            "Wysłanie formularza kontaktowego nie tworzy automatycznie umowy. Współpraca, warunki komercyjne, terminy albo zakres projektu muszą zostać uzgodnione oddzielnie.",
          ],
        },
        {
          heading: "5. Dozwolone korzystanie",
          paragraphs: [
            "Możesz przeglądać stronę w celach prywatnych lub biznesowo-informacyjnych. Nie wolno zakłócać działania strony, obchodzić zabezpieczeń, przeciążać serwisu, scrapować go w sposób zakłócający działanie, próbować nieautoryzowanego dostępu do systemów używanych przez stronę ani dostarczać treści bezprawnych.",
          ],
        },
        {
          heading: "6. Własność intelektualna",
          paragraphs: [
            "O ile nie wskazano inaczej, treści strony, układ, grafiki, kod i materiały portfolio są chronione prawem autorskim albo innymi prawami własności intelektualnej.",
            "Możesz udostępniać linki do publicznych stron. Ponowne wykorzystanie treści wykraczające poza cytat, użytek prywatny albo inne ustawowe wyjątki wymaga wcześniejszej zgody operatora albo właściwego uprawnionego.",
          ],
        },
        {
          heading: "7. Usługi zewnętrzne i linki",
          paragraphs: [
            "Strona może zawierać linki do zewnętrznych serwisów, repozytoriów, profili społecznościowych albo usług osób trzecich. Operator nie odpowiada za treść, dostępność ani zasady usług zewnętrznych po opuszczeniu tej strony.",
          ],
        },
        {
          heading: "8. Dostępność i zmiany",
          paragraphs: [
            "Operator może w dowolnym czasie aktualizować, zawieszać albo usuwać części strony. Strona jest publicznym portfolio i może być czasowo niedostępna z powodu konserwacji, problemów hostingowych, zabezpieczeń albo przerw po stronie usług zewnętrznych.",
          ],
        },
        {
          heading: "9. Odpowiedzialność",
          paragraphs: [
            "Operator dokłada rozsądnych starań, aby strona była aktualna i bezpieczna, ale nie gwarantuje nieprzerwanego działania ani tego, że każda publiczna informacja portfolio będzie zawsze aktualna.",
            "Nic w regulaminie nie ogranicza odpowiedzialności w zakresie, w którym takie ograniczenie byłoby niedopuszczalne na podstawie obowiązującego prawa.",
          ],
        },
        {
          heading: "10. Reklamacje",
          paragraphs: [
            `Reklamacje dotyczące strony albo formularza kontaktowego można zgłaszać na ${PRIVACY_CONTROLLER_EMAIL}. Opisz problem i sposób kontaktu. Operator rozpatrzy reklamację i odpowie na podany adres e-mail, zwykle w ciągu 14 dni.`,
          ],
        },
        {
          heading: "11. Prywatność",
          paragraphs: [
            "Informacje o przetwarzaniu danych osobowych, w tym klauzula informacyjna z art. 13 RODO, pamięć przeglądarki, analityka i obsługa formularza kontaktowego, znajdują się w Polityce prywatności.",
          ],
        },
        {
          heading: "12. Zmiany regulaminu",
          paragraphs: [
            "Regulamin może być aktualizowany, gdy zmieni się strona, używane narzędzia albo wymagania prawne. Aktualna wersja jest publikowana na tej stronie wraz z datą ostatniej aktualizacji.",
          ],
        },
      ],
    },
  },
} satisfies Record<Locale, Record<LegalPageKey, LegalContent>>;

export function getLegalContent(
  locale: Locale,
  pageKey: LegalPageKey,
): LegalContent {
  return legalContent[locale][pageKey];
}

export function getPrivacyContent(locale: Locale): LegalContent {
  return getLegalContent(locale, "privacy");
}

export function legalPagePath(locale: Locale, pageKey: LegalPageKey): string {
  return localePath(locale, `/${pageKey}`);
}

export const legalPageKeys = [
  "privacy",
  "terms",
] as const satisfies readonly LegalPageKey[];

export const legalFooterLinks: Record<
  Locale,
  { key: LegalPageKey; label: string; href: string }[]
> = {
  en: [
    { key: "privacy", label: "Privacy", href: legalPagePath("en", "privacy") },
    { key: "terms", label: "Terms", href: legalPagePath("en", "terms") },
  ],
  pl: [
    {
      key: "privacy",
      label: "Polityka prywatności",
      href: legalPagePath("pl", "privacy"),
    },
    { key: "terms", label: "Regulamin", href: legalPagePath("pl", "terms") },
  ],
};

export const privacyFormNotice: Record<
  Locale,
  { beforeLink: string; linkLabel: string; afterLink: string }
> = {
  en: {
    beforeLink:
      "By submitting, you acknowledge the GDPR processing described in the ",
    linkLabel: "Privacy Policy",
    afterLink: ".",
  },
  pl: {
    beforeLink:
      "Wysyłając formularz, zapoznajesz się z zasadami RODO opisanymi w ",
    linkLabel: "Polityce prywatności",
    afterLink: ".",
  },
};

export const privacyFooterLabel: Record<Locale, string> = {
  en: "Privacy",
  pl: "Polityka prywatności",
};
